name: eip7702
description: Dart library for EIP-7702 delegated transactions enabling smart account authorization and gas abstraction.
homepage: https://variance.space
repository: https://github.com/vaariance/eip-7702.git
issue_tracker: https://github.com/vaariance/eip-7702/issues
version: 1.1.1

environment:
  sdk: ^3.7.2

dependencies:
  web3dart: ^3.0.1
  wallet: ^0.0.18
  freezed_annotation: ^3.1.0
  http: ^1.6.0


dev_dependencies:
  build_runner: ^2.10.4
  freezed: ^3.2.3
  mocktail: ^1.0.4
  test: ^1.28.0
  eip1559: ^0.6.2
  lints: ^6.0.0

topics:
  - wallets
  - ethereum
  - web3
  - account-abstraction

