name: eip7702
description: Barebones implementation of EIP-7702 tx type
homepage: https://variance.space
repository: https://github.com/vaariance/eip-7702.git
issue_tracker: https://github.com/vaariance/eip-7702/issues
version: 1.0.0-r1

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  web3dart: ^3.0.1
  wallet: ^0.0.18
  freezed_annotation: ^3.1.0


dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner: ^2.10.4
  freezed: ^3.2.3

topics:
  - wallets
  - ethereum
  - web3
  - account-abstraction

